# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CastPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.TextField(blank=True, db_column='Person_ID', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('birth_year', models.TextField(blank=True, db_column='Birth Year', null=True)),
                ('death_year', models.TextField(blank=True, db_column='Death Year', null=True)),
            ],
            options={
                'db_table': 'cast_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CastRe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.TextField(blank=True, db_column='Movie_ID', null=True)),
                ('person_id', models.TextField(blank=True, db_column='Person_ID', null=True)),
                ('characters', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cast_re',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrewPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.TextField(blank=True, db_column='Person_ID', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('birth_year', models.TextField(blank=True, db_column='Birth Year', null=True)),
                ('death_year', models.TextField(blank=True, db_column='Death Year', null=True)),
                ('primary_profession', models.TextField(blank=True, db_column='Primary Profession', null=True)),
            ],
            options={
                'db_table': 'crew_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrewRe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.TextField(blank=True, db_column='Movie_ID', null=True)),
                ('person_id', models.TextField(blank=True, db_column='Person_ID', null=True)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
            ],
            options={
                'db_table': 'crew_re',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenreRe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.TextField(blank=True, db_column='Movie_ID', null=True)),
                ('genre_id1', models.TextField(blank=True, db_column='genre_ID1', null=True)),
                ('genre_id2', models.TextField(blank=True, db_column='genre_ID2', null=True)),
                ('genre_id3', models.TextField(blank=True, db_column='genre_ID3', null=True)),
            ],
            options={
                'db_table': 'genre_re',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenresTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres_name', models.TextField(blank=True, db_column='Genres_Name', null=True)),
                ('genres_id', models.TextField(blank=True, db_column='Genres_ID', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'genres_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoviesGenre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movies_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoviesMovie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('popularity', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'movies_movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(blank=True, db_column='X', null=True)),
                ('movie_id', models.TextField(blank=True, db_column='Movie_ID', null=True)),
                ('average_rating', models.FloatField(blank=True, db_column='Average.Rating', null=True)),
                ('number_of_votes', models.IntegerField(blank=True, db_column='Number.of.Votes', null=True)),
                ('level', models.TextField(blank=True, db_column='Level', null=True)),
                ('popular', models.TextField(blank=True, db_column='Popular', null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.TextField(blank=True, db_column='Movie_ID', null=True)),
                ('version_order', models.IntegerField(blank=True, db_column='Version_order', null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('language', models.TextField(blank=True, db_column='Language', null=True)),
                ('isoriginaltitle', models.IntegerField(blank=True, db_column='isOriginalTitle', null=True)),
            ],
            options={
                'db_table': 'title',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='genre',
            name='movie',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
